version: '3'
services:
  db:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./queries:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: taskworld
  app:
    build: .
    container_name: app
    ports:
      - 8080:8080
    restart: always
    environment:
      MYSQL_ADDRESS: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    depends_on: 
      - db
  prom:
    image: prom/prometheus:latest
    container_name: prom
    restart: always
    volumes: 
      - ./prometheus:/etc/prometheus
      - ./prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    depends_on: 
      - app
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    volumes:
      - ./grafana_data:/var/lib/grafana
    environment:
        - GF_SECURITY_ADMIN_PASSWORD=1234
    depends_on:
        - prom
    ports:
        - 3000:3000