version: '2'
services:
  web:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./queries:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: taskworld
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234